# Generated by Django 3.1.7 on 2021-04-19 17:01

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210419_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilePics/user.png', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profilePics/'),
        ),
    ]
