# Generated by Django 3.1.7 on 2021-05-02 04:28

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210419_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilePics/colorfull_user.png', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profilePics/'),
        ),
    ]
